CC=clang
CFLAGS=-lev
ANALYZEFLAGS=--analyze -Wall
DEBUGFLAGS=-O0 -g
PRODFLAGS=-O4
RAGEL=ragel
RAGELFLAGS=-G2 -C
SOURCEFILES=$(RAGELSOURCE) midnight.c midnight_worker.c
RAGELSOURCE=$(RAGELFILES:.rl=.c)
RAGELFILES=midnight_parser.rl
APPNAME=midnight

all: debug

$(APPNAME): $(RAGELSOURCE) $(SOURCEFILES)
	$(CC) $(CFLAGS) $(SOURCEFILES) -o $(APPNAME)

analyze: $(RAGELSOURCE) $(SOURCEFILES)
	$(CC) $(CFLAGS) $(ANALYZEFLAGS) $(SOURCEFILES)

debug: $(RAGELSOURCE) $(SOURCEFILES)
	$(CC) $(CFLAGS) $(DEBUGFLAGS) $(SOURCEFILES) -o $(APPNAME)

product: $(RAGELSOURCE) $(SOURCEFILES)
	$(CC) $(CFLAGS) $(PRODFLAGS) $(SOURCEFILES) -o $(APPNAME)

$(RAGELSOURCE): $(RAGELFILES)
	$(RAGEL) $(RAGELFLAGS) $(RAGELFILES)

clean:
	rm -rf $(APPNAME) $(APPNAME).dSYM a.out a.out.dSYM $(SOURCEFILES:.c=.plist) $(RAGELSOURCE:.c=.plist) $(RAGELSOURCE) *.o